server:
  port: 8080
  contextPath: /ecr

spring:
  profiles: local,default
datasource:
  ecrone:
    url: jdbc:mysql://localhost:3306/ECR_R1
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect